{"trial_id": "0000", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "sigmoid"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 1, "max_value": 120, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}], "values": {"activation": "relu", "first_units": 75, "num_layers": 2, "units_0": 9, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 4, "tuner/round": 0, "units_1": 1}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras_tuner/tuners/hyperband.py\", line 425, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras_tuner/engine/hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/var/folders/m6/5m5yr4vx1hnfwqqw70nydyqr0000gn/T/__autograph_generated_file5clbgno_.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nValueError: in user code:\n\n    File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1080, in train_step\n        y_pred = self(x, training=True)\n    File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"/Users/davidlevy/Documents/Work/education/berkeley_ds/module_challenges/deep-learning-challenge/.venv/lib/python3.9/site-packages/keras/src/engine/input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 2), found shape=(None, 63)\n\n"}